name = "backend"
compatibility_date = "2024-07-16"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiN2M4MjBiZjEtNGYzYS00MTc2LTlkNWYtZDdlNTc0MWIzZWIzIiwidGVuYW50X2lkIjoiMWUzOGExMjdiMDIxMGJmYjllNjliODI4YzBjNmIzZDk5ZWZlYjExZGQ2ZjJjYzkwZTM2Y2U1OTQwODQ3MTljZiIsImludGVybmFsX3NlY3JldCI6IjE5MjU3OTkyLTU1NzQtNGMyYy1hNWY4LWI0ZjJhN2RlZjAwMyJ9.zljHyXCwqJ3vGGTNpx3ZQ_ScKRmuefJvu0UtL1FhpN8"
