name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMTg1NDhiZWItMTU4NC00NTJmLTk1YjMtNzUwM2NlZDBkZmY3IiwidGVuYW50X2lkIjoiMGNkNDMxMmUwMDk3NjU1YjYxMzRjNGE4NmY3MDc0NzE3NDUzYjgyNzJlMGIzMTM1MWUxZjI5MzIzZjgwMDIzOSIsImludGVybmFsX3NlY3JldCI6ImEwZGI3MGU1LTU2MDMtNDE0Yi05ZDFhLTYyOThmMWQ2OGQ1MyJ9.m5p1vdyCLtt76CBj-MZcVs0r9WFRoszBUPoJNLeCc5M"

JWT_SECRET="MY_SECRET"